version: '2'
services:
  zk:
    image: "jplock/zookeeper:3.5.1-alpha"
    expose: 
      - 2181 
    ports:
      - 8085:8085
    logging: 
      driver: none
  zkpacket:
    build: .
    network_mode: service:zk
  zkload:
    build: .
    command: ./zkload/zkload --zk-host=zk
    links: 
      - zk
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - '-config.file=/etc/prometheus/prometheus.yaml'
    expose:
      - 9090
    ports:
      - 9090:9090
    links:
      - zk
