version: '2'
services:
  zk:
    build:
      dockerfile: Dockerfile.zookeeper
      context: docker/
    expose: 
      - 2181 
      - 8085
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
  zk-2:
    build:
      dockerfile: Dockerfile.zookeeper
      context: docker/
    expose: 
      - 2181 
      - 8085
  zk-3:
    build:
      dockerfile: Dockerfile.zookeeper
      context: docker/
    expose: 
      - 2181 
      - 8085
  zkpacket:
    build: 
      dockerfile: docker/Dockerfile.zkpacket
      context: .
    network_mode: service:zk
    depends_on: 
      - zk
  zkpacket-2:
    build: 
      dockerfile: docker/Dockerfile.zkpacket
      context: .
    network_mode: service:zk-2
  zkpacket-3:
    build: 
      dockerfile: docker/Dockerfile.zkpacket
      context: .
    network_mode: service:zk-3
  zkload:
    build: .
    command: ./zkload/zkload --zk-host=zk
    depends_on: 
      - zk
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      # - prometheus_data:/prometheus
      - /etc/localtime:/etc/localtime:ro
    command:
      - '-config.file=/etc/prometheus/prometheus.yaml'
      - '-storage.local.path=/prometheus'
      - '-log.level=info'
    expose:
      - 9090
    ports:
      - 9090:9090
    links:
      - zk:zk
      - zk-2
      - zk-3
      - cadvisor:cadvisor
  cadvisor:
    image: google/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    expose:
      - 8080
    logging: 
      driver: none
  grafana:
    image: grafana/grafana:4.1.2
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    env_file:
      - grafana/config.monitoring
    logging: 
      driver: none
volumes:
    prometheus_data:

