version: '2'
services:
  zk:
    image: "jplock/zookeeper:3.5.1-alpha"
    expose: 
      - 2181 
      - 8085
    ports:
      - 8085:8085

  zkpacket:
    build: .
    network_mode: service:zk
  zkload:
    build: .
    command: ./zkload/zkload --zk-host=zk
    links: 
      - zk
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      # - prometheus_data:/prometheus
      - /etc/localtime:/etc/localtime:ro
    command:
      - '-config.file=/etc/prometheus/prometheus.yaml'
      - '-storage.local.path=/prometheus'
      - '-log.level=info'
    expose:
      - 9090
    ports:
      - 9090:9090
    links:
      - zk:zk
  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    env_file:
      - prometheus/config.monitoring
    logging: 
      driver: none
volumes:
    prometheus_data:

