// Code generated by "stringer -type=watchOpType"; DO NOT EDIT

package main

import "fmt"

const _watchOpType_name = "opGetDataWopExistsWopGetChildren2W"

var _watchOpType_index = [...]uint8{0, 10, 19, 34}

func (i watchOpType) String() string {
	if i < 0 || i >= watchOpType(len(_watchOpType_index)-1) {
		return fmt.Sprintf("watchOpType(%d)", i)
	}
	return _watchOpType_name[_watchOpType_index[i]:_watchOpType_index[i+1]]
}
